name: CI

#event trigger (ketika push dan pr maka akan menjalankan jobs dibawah)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
y
# jobs berisi beberapa tugas
jobs:

  # tugas pertama adalah melakukan testing
  test:
    #menjalankan dengan environment ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...


    - name: Build
      run: go build -o app .
      
    - name: Show List
      run: ls -l


  # melakukan tugas membuild dan membuat release
  release:
    #needs maksudnya jika job test belum selesei maka job ini tidak dijalankan
    needs: [test]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASER }}
